name=input('Please enter your name: ')
print(f'Hello {name}! Welcome to Matlib game!')
adj1=input('Adjective: ')
noun=input('Noun: ')
adj2=input('Adjective: ')
adj3=input('Adjective: ')
noun2=input('Noun: ')
adj4=input('Adjective: ')
noun3=input('Noun: ')
adj5=input('Adjective: ')
noun4=input('Noun: ')
adj6=input('Adjective: ')
# print(f'The {noun} is so {adjective1} and {adjective2}')
# print('The {} is so {} and {}'.format(noun,adjective1,adjective2))
madlib=f'One day, I was walking through the {adj1} forest when I stumbled upon a {noun}. It was {adj2} and looked very {adj3}. Curious, I decided to take a closer look. Suddenly, a {noun2} appeared out of nowhere! It was {adj4} and seemed to be guarding something. I reached down and picked up a {noun3}, which turned out to be a {adj5} treasure! I couldn\'t believe my eyes. It was a {noun4} unlike any I\'d ever seen before. What a {adj6} adventure!'
print(madlib)